version: '3'

services:
  device1:
    build:
      context: .
    image: ubuntu-python:latest
    networks:
      internal_network:
        ipv4_address: 186.25.0.2
    container_name: dispositivo_1

  device2:
    build:
      context: .
    image: ubuntu-python:latest
    networks:
      internal_network:
        ipv4_address: 186.25.0.3
    container_name: dispositivo_2

  device3:
    build:
      context: .
    image: ubuntu-python:latest
    networks:
      internal_network:
        ipv4_address: 186.25.0.4
    container_name: dispositivo_3

  device4:
    build:
      context: .
    image: ubuntu-python:latest
    networks:
      internal_network:
        ipv4_address: 186.25.0.5
    container_name: dispositivo_4

networks:
  internal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 186.25.0.0/16