version: '3'

services:
  device1:
    image: ubuntu:latest
    command: sleep infinity
    networks:
      internal_network:
        ipv4_address: 172.20.0.2

  device2:
    image: ubuntu:latest
    command: sleep infinity
    networks:
      internal_network:
        ipv4_address: 172.20.0.3

  device3:
    image: ubuntu:latest
    command: sleep infinity
    networks:
      internal_network:
        ipv4_address: 172.20.0.4

  device4:
    image: ubuntu:latest
    command: sleep infinity
    networks:
      internal_network:
        ipv4_address: 172.20.0.5

  pinger:
    build: .
    networks:
      internal_network:

networks:
  internal_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16